import os

try:
	from comtypes import client
	api = client.GetModule(r"C:\Program Files\Nuance\OPCaptureSDK20\Include\IproPlus.tlb")	
except:
	print("Comtypes is not installed on your system or Please update path in OCR-mod-command.py file.")


def GetOCRByOmniPage(strInput):
	obj = client.CreateObject(api.Engine)
	obj.Init()
	doc = obj.Documents.Add()
	z = doc.LoadImage(strInput)
	
	strOutput = os.path.join(os.getcwd(),"output.txt")
	z.ConvertToDirectTXT(strOutput,0)

	if os.path.exists(strOutput):
		with open(strOutput,'r') as f:
			strText = f.read()
		
		os.remove(strOutput)
		return strText
	else:
		print("Output file did not generated by Omnipage.")
		return ""

	
# if __name__ == "__main__":
# 	print(GetOCRByOmniPage(r"F:\c210k_pdf.pdf").encode('utf-8'))
